// <auto-generated />
namespace VideoSystem.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class deleteVideoMd5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deleteVideoMd5));
        
        string IMigrationMetadata.Id
        {
            get { return "201612060659502_deleteVideoMd5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
