// <auto-generated />
namespace VideoSystem.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class alter1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alter1));
        
        string IMigrationMetadata.Id
        {
            get { return "201611291516382_alter1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
