// <auto-generated />
namespace VideoSystem.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class modifyUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modifyUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201701191328397_modifyUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
