// <auto-generated />
namespace VideoSystem.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class modifyVideo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modifyVideo));
        
        string IMigrationMetadata.Id
        {
            get { return "201701161343033_modifyVideo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
